### ISSUE TITLE
Crash after the update

### ISSUE THREAD

**Issue by adadada19** [mikeoverbay/TankExporter#108] opened 2024-06-05 19:16 UTC
After 1.25 update couldn't start the programm (crashes on loading nodes 01)

**Comment by Williamsilliam** [comment] 2024-06-05 22:16
same thing here

**Comment by ETnannn** [comment] 2024-06-06 17:01
the same problem, have you solved it?

**Comment by adadada19** [comment] 2024-06-06 17:07
> the same problem, have you solved it?

no, tried to reinstall/clear game/res_mods path, didn't work

**Comment by Cerberus50** [comment] 2024-06-07 15:51
Same for me. Uninstal (RévoUninstal) register clear. Reinstall = didn’t work. Loading node 1 = crash

**Comment by Cerberus50** [comment] 2024-06-07 16:06
I think Mike dropped the TE updates

**Comment by adadada19** [comment] 2024-06-07 18:21
> I think Mike dropped the TE updates

Where?

**Comment by goosedoeshonk** [comment] 2024-06-07 21:52
same problem here, will we just have to wait this out until its fixed? what i can tell from other programs where this happens is its basically just a missing designation to an object, or simply, the code broke

**Comment by QuietShow** [comment] 2024-06-15 10:47
There are 3 "gui-parts" 1. 2 and 3 in the "res/packages" of the game. There were only 2 before. This is why T.E crashes

**Comment by QuietShow** [comment] 2024-06-15 10:49
simply, you just need to empty the gui-part3 into gui-part2 using winrar, if you know what you're doing. but make sure to make a backup of the wot gui-parts (gui-part1; gui-part2; gui-part3) before editing them.
After doing that WoT will not open but you can paste the backup files into wot and then wot will work again.
Here's a guide: (any question ask me)

**Comment by QuietShow** [comment] 2024-06-15 10:50
**WARNING1:** BEFORE DOING ANYTHING, DO A BACKUP OF gui-part2 AND gui-part3, LOCATED INSIDE res/packages, IN WOT FILES.
nazref, or anyone needing help, it's not hard to make what he (Cerberus) said, but make sure to make a backup of gui-part3 and gui-part2, because if you are going to empty the gui-part3 into gui-part2, you are going to modify the gui-part2.

I'll call the 1st gui-part2 and gui-part3 MAIN.

An easier way to do is to extract gui-part3 to [your choice, as long as you know where you are extracting it] and then open gui-part2 with winrar and copy the files from gui-part3 and paste them inside gui-part2. After that you may change the name of the gui-part3, like Cerberus did, to gui-part3nul, or just remove the gui-part3 --> I removed.

PS.: If you can't extract the .pkg file (the MAIN file), which is normal, open winrar and extract the folder that pops up when you open MAIN gui-part2 not the files inside that folder.

**WARNING2:** AFTER THESE STEPS, DO A BACKUP OF THE gui-part2 THAT YOU'VE CHANGED, BUT **DO NOT** REPLACE THE MAIN gui-part2 DONE IN [WARNING1], so you don't need to repeat everytime this process.

After that WoT will no longer work. What to do? Copy and Paste the MAIN files into WoT res/packages file once again. IF YOU CHANGED THE gui-part3 TO gui-part3nul REMOVE THE gui-part3nul and add the MAIN files.

AGAIN, BEFORE EDITING SOMETHING:

- ALWAYS make a backup
- if you don't know what you're doing tell me, because I eventually can make a tutorial until mikeoverbay doesn't fix this.

**Comment by QuietShow** [comment] 2024-06-15 10:50
What Cerberus said in the other issue:

I made a backup copy of the gui-part2, I opened the gui-part2 and gui-part3 with winrar and I emptied the part-3 into the part-2 then I renamed the gui-part3 in gui-part3nul.

And TE was resurrected! But WOT di'nt WORK NOW

warning made a back up of the 3 gui-part before processed .

COPY/PASTE 3 back up gui-part to RES/PACKAGE after CLOSE T.E. And WoT works now

**Comment by adadada19** [comment] 2024-06-15 22:20
It's certainly more of a crutch not a solution. I still want to use wot while using tank exporter

**Comment by mikeoverbay** [comment] 2024-07-19 15:57
OK people.. Im back.
For the last 6 months, I have been in massive pine do to spurs in my spine at the base of my neck.
I am going to work on TE and see if I can fix the bug caused by the additional pkgs,
Can you people help answer the questions that you can in issues. close them if you fix their problem.
Its very hard to type with this right hand nearly useless from the nerves being pinched.

**Comment by mikeoverbay** [comment] 2024-07-19 18:58
> There are 3 "gui-parts" 1. 2 and 3 in the "res/packages" of the game. There were only 2 before. This is why T.E crashes

This led me right to the fix.. tanks!

Try version 140 folks.
Let me know here!!

**Comment by mikeoverbay** [comment] 2024-08-07 15:26
closing this as its fixed.

**Closed by mikeoverbay** 2024-08-07 15:26 UTC
